version: '3.9'
services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./src:/app/src
    env_file:
      - .env
    command:
      go run src/main.go